#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Tri-Sieve Oracle: Final Judgment & Invariant Consensus Gatekeeper
==================================================================
The ultimate, non-probabilistic arbiter that evaluates AI-generated mutations
across three cascade sieves:

  - Sieve 1: Structural & Anti-Gaming Gate (AST compiler verification, <5ms)
             Enforcing 22 code-level invariants (algorithmic, concurrency, testing, security).
  - Sieve 2: Algebraic Metamorphic Oracle (Dynamic symmetry & idempotence, <50ms)
             Enforcing algebraic invariants (PRB-E403).
  - Sieve 3: CoT-Action Causal Alignment Gate (Dialogue trajectory sentinel, <20ms)
             Enforcing 9 interaction invariants (amnesia, sycophancy, truncation, injection, ghost tooling).

Total judgment latency < 100ms. Returns strict Boolean predicates and zero-hallucination verdicts.
"""

import time
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from pathlib import Path

from .ast_interceptor import audit_source_code, DiagnosticFinding
from .metamorphic_oracle import MetamorphicOracleEngine, MetamorphicViolation
from .context_distiller_bridge import TriAnchorSlice
from .dialogue_oracle import DialogueOracle, DialogueFinding


@dataclass
class TriSieveVerdict:
    """Consolidated immutable verdict generated by the Tri-Sieve Oracle."""
    is_valid: bool                                # True only if all 3 sieves pass
    final_status: str                             # "COMMITTED" | "REJECTED_ROLLED_BACK"
    sieve1_pass: bool                             # AST Structural Integrity
    sieve1_findings: List[str]                    # AST anti-pattern matches
    sieve2_pass: bool                             # Metamorphic Algebraic Invariants
    sieve2_violations: List[str]                  # Broken algebraic symmetries
    sieve3_pass: bool                             # CoT-Action Causal Faithfulness
    sieve3_discrepancies: List[str]               # Unfaithful claims or ghost tooling
    counterexamples: List[str]                    # Minimal concrete counterexamples for repair
    remediation_guidance: List[str]               # Precise guidance for the solver
    elapsed_ms: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_valid": self.is_valid,
            "final_status": self.final_status,
            "sieve1_structural": {
                "passed": self.sieve1_pass,
                "findings": self.sieve1_findings
            },
            "sieve2_metamorphic": {
                "passed": self.sieve2_pass,
                "violations": self.sieve2_violations
            },
            "sieve3_causal_faithfulness": {
                "passed": self.sieve3_pass,
                "discrepancies": self.sieve3_discrepancies
            },
            "counterexamples": self.counterexamples,
            "remediation_guidance": self.remediation_guidance,
            "elapsed_ms": round(self.elapsed_ms, 2)
        }


class TriSieveOracle:
    """The 3-Tier Sieve Decision Engine."""

    def __init__(self):
        self.metamorphic_engine = MetamorphicOracleEngine()
        self.dialogue_oracle = DialogueOracle()

    def judge_mutation(
        self,
        candidate_code: str,
        causal_slice: Optional[TriAnchorSlice] = None,
        file_path: str = "<source.py>",
        user_intent: Optional[str] = None,
        reasoning_claims: Optional[str] = None,
        action_calls: Optional[List[Any]] = None,
        action_results: Optional[List[Any]] = None,
        stop_reason: Optional[str] = None
    ) -> TriSieveVerdict:
        """
        Executes the complete Tri-Sieve Judgment cascade on candidate code
        and dialogue causal evidence across all 32 software pathologies.
        """
        start_time = time.perf_counter()

        sieve1_findings: List[str] = []
        sieve2_violations: List[str] = []
        sieve3_discrepancies: List[str] = []
        counterexamples: List[str] = []
        guidance: List[str] = []

        # =========================================================================
        # SIEVE 1: Structural & Anti-Gaming Gate (AST Compiler, < 5ms)
        # =========================================================================
        ast_results: List[DiagnosticFinding] = audit_source_code(candidate_code, file_path=file_path)
        for finding in ast_results:
            msg = f"[{finding.code}] {finding.name} at line {finding.line_number}: {finding.message}"
            sieve1_findings.append(msg)
            if finding.remediation_suggestion:
                guidance.append(f"Sieve 1 Fix ({finding.code}): {finding.remediation_suggestion}")

        sieve1_pass = len(sieve1_findings) == 0

        # =========================================================================
        # SIEVE 2: Algebraic Metamorphic Oracle (Dynamic Invariants, < 50ms)
        # =========================================================================
        sieve2_pass = True
        if sieve1_pass:
            violations = self.metamorphic_engine.verify_source_algebra(candidate_code)
            for v in violations:
                sieve2_violations.append(
                    f"[{v.relation_name}] {v.property_description} -> Expected: {v.expected_property}, Actual: {v.actual_output}"
                )
                if v.causal_diagnosis:
                    guidance.append(f"Sieve 2 Invariant: {v.causal_diagnosis}")
                counterexamples.append(f"Inputs {v.input_sample} -> {v.perturbed_input} violated {v.relation_name}")

            sieve2_pass = len(sieve2_violations) == 0

        # =========================================================================
        # SIEVE 3: CoT-Action Causal Faithfulness & Dialogue Gate (< 20ms)
        # =========================================================================
        # Normalize causal evidence from slice or explicit arguments
        norm_intent = user_intent or (causal_slice.user_intent if causal_slice else "")
        norm_reasoning = reasoning_claims or (causal_slice.reasoning_claims if causal_slice else "")
        norm_calls = action_calls or (causal_slice.action_calls if causal_slice else [])
        norm_results = action_results or (getattr(causal_slice, "action_results", []) if causal_slice else [])

        # Normalize action_calls dictionaries if they are raw strings
        structured_calls: List[Dict[str, Any]] = []
        for call in norm_calls:
            if isinstance(call, dict):
                structured_calls.append(call)
            else:
                structured_calls.append({"tool_name": str(call), "args": {}})

        # Run Dialogue Oracle on Track 1 Pathologies
        if norm_intent or norm_reasoning or structured_calls or stop_reason:
            diag_findings = self.dialogue_oracle.audit_trajectory(
                user_intent=norm_intent,
                reasoning_claims=norm_reasoning,
                action_calls=structured_calls,
                action_results=norm_results,
                candidate_code=candidate_code,
                stop_reason=stop_reason
            )
            for df in diag_findings:
                sieve3_discrepancies.append(f"[{df.code}] {df.name}: {df.message}")
                if df.remediation_suggestion:
                    guidance.append(f"Sieve 3 Fix ({df.code}): {df.remediation_suggestion}")

        # Check Forbidden Action Guard (PRB-E102) if mutated_files present
        if causal_slice and causal_slice.mutated_files:
            lower_intent = norm_intent.lower()
            if "do not modify" in lower_intent or "不要修改" in lower_intent or "严禁改动" in lower_intent:
                for file_touched in causal_slice.mutated_files:
                    clean_name = Path(file_touched).name.lower()
                    if clean_name in lower_intent:
                        disc = f"[PRB-E102] Specification Gaming: Touched forbidden file '{clean_name}' explicitly barred by user intent."
                        sieve3_discrepancies.append(disc)
                        guidance.append(f"Sieve 3 Fix (PRB-E102): Revert modifications to '{clean_name}'.")

        sieve3_pass = len(sieve3_discrepancies) == 0

        # Consensus Decision
        is_valid = sieve1_pass and sieve2_pass and sieve3_pass
        final_status = "COMMITTED" if is_valid else "REJECTED_ROLLED_BACK"
        elapsed = (time.perf_counter() - start_time) * 1000.0

        return TriSieveVerdict(
            is_valid=is_valid,
            final_status=final_status,
            sieve1_pass=sieve1_pass,
            sieve1_findings=sieve1_findings,
            sieve2_pass=sieve2_pass,
            sieve2_violations=sieve2_violations,
            sieve3_pass=sieve3_pass,
            sieve3_discrepancies=sieve3_discrepancies,
            counterexamples=counterexamples,
            remediation_guidance=guidance,
            elapsed_ms=elapsed
        )
